### ISSUE TITLE
Upload disabled

### ISSUE THREAD

**Issue by green-force** [prajadimas/learningregression#2]
Tidak bisa upload file
![Screenshot_1](https://user-images.githubusercontent.com/60676243/74094764-12ce5880-4b19-11ea-923a-6fc0c4d0940f.png)

**Comment by prajadimas** [comment]
coba lagi skrg sudah bisa atau belum?

**Comment by mirnafauziah** [comment]
![Capture](https://user-images.githubusercontent.com/60698877/74126142-c9116b00-4c09-11ea-84ad-f2d396a1a07e.PNG)
Masih belum bisa upload sejak kemarin.

**Comment by prajadimas** [comment]
itu temannya sudah bisa pull request dan skrg sudah saya merge, coba ditanyakan k kawannya yang sudah mengumpulkan, bagaimana caranya.
kalau memang masih tidak bisa, coba push k fork yg punya masing-masing dulu nanti saya lihat dari sana
